server:
  port: 8484

spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/broker_schema?createDatabaseIfNotExist=true
    username: 8484
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver