spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  liquibase:
    enabled: true

logging:
  level:
    root: warn
    com.broker_manager: warn
    org.springframework.security.web.FilterChainProxy: debug

springdoc:
  swagger-ui:
    path: /