spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/broker_schema
    username: u
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: 1

logging:
  level:
    root: warn
    com.broker_manager: warn
    org.springframework.security.web.FilterChainProxy: debug

springdoc:
  swagger-ui:
    path: /
