server:
  port: 8484

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/broker_schema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: 1

logging:
  level:
    root: warn
    com.broker_manager: warn
    org.springframework.security.web.FilterChainProxy: debug

springdoc:
  swagger-ui:
    path: /