server:
  port: 8080

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/broker_schema?createDatabaseIfNotExist=true
      username: 8484
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver